### ISSUE TITLE
About the weight coefficient \lambda

### ISSUE THREAD

**Issue by antct** [woohwanjung/dual#1]
Hi, thanks for your nice work.
I have a question about the model performance under different values of \lambda(the default value of \lambda is 1e-4)?
Thanks!

**Comment by woohwanjung** [comment]
Thanks for your interest in our work!

Unfortunately, I cannot check the data because I graduated from the school.
As I remember, the performance is stable when we use a smaller lambda (ex: 1e-5, 1e-6). 
However, it is degraded when using a much larger lambda (ex: 0.1, 0.01).

Thanks!

**Comment by antct** [comment]
Thanks for your help!
